# fastQC

fastqc /media/Shared/Data/chum/populations/cleanSeqs/CMKALA03_0011.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMKALA03_0010.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMKALA03_0009.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMKALA03_0008.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMKALA03_0007.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMKALA03_0006.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMKALA03_0005.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMKALA03_0004.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMKALA03_0044.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMKALA03_0037.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMUW10_0016.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMUW10_0015.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMUW10_0012.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMUW10_0011.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMUW10_0010.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMUW10_0009.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMUW10_0008.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMUW10_0007.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMUW10_0004.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMUW10_0003.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMUW10_0002.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMUW10_0001.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMHAMM10_0002.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0095.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0093.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0090.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0087.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0085.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0083.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0081.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0075.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0071.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0068.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0066.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0062.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0059.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0057.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0056.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0053.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0050.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0047.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0034.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0033.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0032.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0027.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0022.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0020.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0019.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0018.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0017.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0016.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0015.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0009.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0003.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94S_0001.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0091.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0086.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0085.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0084.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0083.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0076.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0075.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0074.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0066.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0064.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0061.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0059.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0058.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0056.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0052.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0047.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0046.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0045.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0039.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0036.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0035.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0033.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0032.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0028.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0027.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0026.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0024.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0022.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0019.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0018.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0012.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSHERW94F_0010.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMLILLIW11_0099.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMLILLIW11_0096.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMLILLIW11_0095.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMLILLIW11_0089.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMLILLIW11_0087.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMLILLIW11_0085.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMLILLIW11_0080.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMLILLIW11_0079.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMLILLIW11_0077.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMLILLIW11_0063.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMLILLIW11_0061.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMLILLIW11_0053.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMLILLIW11_0048.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMLILLIW11_0047.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMLILLIW11_0037.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMLILLIW11_0035.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMLILLIW11_0032.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMLILLIW11_0031.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMLILLIW11_0030.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMLILLIW11_0011.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMKALA03_0050.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMKALA03_0049.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMKALA03_0048.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMKALA03_0046.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMHAMM10_0056.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMHAMM10_0040.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMHAMM10_0033.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMHAMM10_0030.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSTILL10_0080.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSTILL10_0067.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSTILL10_0061.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSTILL10_0059.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSTILL10_0055.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSTILL10_0047.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSTILL10_0044.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSTILL10_0043.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSTILL10_0037.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSTILL10_0036.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSTILL10_0033.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSTILL10_0029.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSTILL10_0020.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSTILL10_0014.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSTILL10_0009.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSTILL10_0006.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSNOH10_0106.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSNOH10_0105.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSNOH10_0104.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSNOH10_0102.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSNOH10_0090.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSNOH10_0089.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSNOH10_0088.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSNOH10_0085.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSNOH10_0072.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSNOH10_0069.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSNOH10_0062.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSNOH10_0058.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSNOH10_0038.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSNOH10_0034.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSNOH10_0027.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSNOH10_0026.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSKOO10_0041.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSKOO10_0040.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSKOO10_0036.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSKOO10_0035.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSKOO10_0033.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSKOO10_0018.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSKOO10_0013.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSKOO10_0012.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSKOO10_0011.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSKOO10_0010.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSKOO10_0009.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSKOO10_0008.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSKOO10_0007.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSKOO10_0006.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSKOO10_0004.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSKOO10_0002.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMKALA03_0041.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMKALA03_0036.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMKALA03_0025.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMKALA03_0024.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMKALA03_0017.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMKALA03_0012.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSQUA10_0058.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSQUA10_0055.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSQUA10_0052.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSQUA10_0046.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSQUA10_0038.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSQUA10_0036.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSQUA10_0031.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSQUA10_0019.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSQUA10_0017.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSQUA10_0016.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSQUA10_0010.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSQUA10_0009.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSQUA10_0008.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSQUA10_0005.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSQUA10_0004.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMSQUA10_0001.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMHAMM10_0029.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMHAMM10_0027.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMHAMM10_0026.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMHAMM10_0025.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMHAMM10_0024.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMHAMM10_0022.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMHAMM10_0018.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMHAMM10_0017.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMHAMM10_0016.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMHAMM10_0015.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMHAMM10_0014.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMHAMM10_0012.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMHAMM10_0011.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMHAMM10_0008.fq.gz \
/media/Shared/Data/chum/populations/cleanSeqs/CMHAMM10_0005.fq.gz -t 6 --extract  --outdir /media/Shared/Data/chum/populations/fastQC

